name: AWS Elastic Beanstalk Deployment

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: "Commit SHA (optional, defaults to latest commit on feature branch)"
        required: false
      dgn:
        description: "Deployment Environment (stag/prod)"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      # dynamic
      DGN: ${{ github.event.inputs.dgn }}
      APP_NAME: ${{ github.event.inputs.dgn }}-dashboard-server2
      # static
      APP_NAME_SHORT: "dashboard-server2"
      AWS_REGION: "ap-south-1"
      DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set commit SHA
        run: |
          if [ -z "${{ github.event.inputs.commit_sha }}" ]; then
            git fetch origin feature
            LATEST_SHA=$(git rev-parse origin/development)
            echo "COMMIT_SHA=$LATEST_SHA" >> $GITHUB_ENV
          else
            echo "COMMIT_SHA=${{ github.event.inputs.commit_sha }}" >> $GITHUB_ENV
          fi

      - name: Checkout specific commit
        uses: actions/checkout@v2
        with:
          ref: ${{ env.COMMIT_SHA }}
          fetch-depth: 0
      - name: print sha 
        run: echo "Final commit SHA ${{ env.COMMIT_SHA }}"
