name: AWS Elastic Beanstalk Deployment

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: "Commit SHA"
        required: false
      dgn:
        description: "Deployment Environment (stag/prod)"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      # dynamic
      DGN: ${{ github.event.inputs.dgn}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set commit SHA
        run: |
          if [ -z "${{ github.event.inputs.commit_sha }}" ]; then
            git fetch origin main
            COMMIT_SHA=$(git rev-parse origin/development)
            echo "Using latest commit SHA from main branch: $COMMIT_SHA"
          else
            COMMIT_SHA="${{ github.event.inputs.commit_sha }}"
            echo "Using provided commit SHA: $COMMIT_SHA"
          fi
          echo "COMMIT_SHA=$COMMIT_SHA" >> $GITHUB_ENV

      - name: Checkout specific commit
        uses: actions/checkout@v2
        with:
          ref: ${{ env.COMMIT_SHA }}
          fetch-depth: 0
      - name: print sha 
        run: echo "Final commit SHA ${{ env.COMMIT_SHA }}"
